apiVersion: batch/v1
kind: Job
metadata:
  name: valven-atlas-hook
  generateName: valven-atlas-hook
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: valven-atlas-hook
        image: alpine:latest
        env:
          - name: XX
            value: $ARGOCD_APP_REVISION 
        command:
          - sh
          - -c
          - |
            echo "{{ .Values.atlashook.name }} {{ .Release.Name }}" && printenv
      restartPolicy: Never
  backoffLimit: 2
