apiVersion: batch/v1
kind: Job
metadata:
  name: valven-atlas-hook
  generateName: valven-atlas-hook
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: valven-atlas-hook
        image: alpine:latest
        command:
          - sh
          - -c
          - |
            echo "$V_TEST $$V_TEST {{ .Values.V_TEST }} {{ .Values.atlashook.name }} {{ .Release.Name }}" && printenv
      restartPolicy: Never
  backoffLimit: 2
